### ISSUE TITLE
document how to convert any item to a dict

### ISSUE THREAD

**Issue by kmike** [scrapy/itemadapter#17]
I think that'd be helpful to explain that `dict(ItemAdapter(item))` gives you a plain version of an item; it could also make sense to add a explicit test for it.

**Comment by elacuesta** [comment]
Docs added in d0184046bbab601b5bbccd25e0b3bc176cd9e369, tests available at https://github.com/scrapy/itemadapter/blob/v0.0.6/tests/test_adapter.py#L149-L153
