### ISSUE TITLE
ItemAdapter docstrings should mention attrs

### ISSUE THREAD

**Issue by kmike** [scrapy/itemadapter#3]
Currently they are focused on dict, scrapy.Item and dataclasses, e.g. `without having to take
    the item's implementation (scrapy.Item, dict, dataclass) into account.`

**Comment by elacuesta** [comment]
Right, I think mentioning no specific type is simpler and easier to maintain. Also removed references to pipelines and middlewares, which are too Scrapy-specific. Addressed by 88c4821ce6ccb37cb0b5bcf4ad517f2431879ba1
